In [1]:
import pandas
print(dir(pandas)

['Categorical',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'ExcelFile',
 'ExcelWriter',
 'Expr',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int64Index',
 'Interval',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseSeries',
 'Term',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt64Index',
 'WidePanel',
 '_DeprecatedModule',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p10',
 '_np_version_under1p11',
 '_np_version_under1p12',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_tslib',
 '_version',
 'api',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'datetime',
 'datetools',
 'descri

In [2]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [3]:
AF = np.array([1,2,3], float)
print(AF)

[1. 2. 3.]


In [4]:
c = np.array([[1,2,3],[4,5,6], [7,8,9]], float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [6]:
x = np.arange(0,1,0.1)
print(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [7]:
a = np.random.normal(loc=50, scale=2, size=(2,2))
print(a)

[[45.69882221 49.53442061]
 [49.7707401  47.55906384]]


In [8]:
a = np.random.normal(loc=50, scale=2, size=(9,9))
print(a)

[[47.28263851 49.6069657  47.03924067 50.13935578 49.71362691 51.23813159
  48.33797637 51.69460794 46.65717089]
 [51.74851218 46.72883672 50.83026388 53.91315674 49.5034558  50.19988648
  51.54134509 46.94918582 50.860565  ]
 [50.31125702 48.95860099 46.26288608 51.39589887 50.30956096 51.06477228
  53.15788133 49.68594131 51.20046254]
 [52.28509254 51.72533024 48.86189943 50.20274912 51.46234691 50.31044139
  49.82077989 50.59331497 52.89676008]
 [49.7282847  51.21506037 49.93792927 52.79981236 46.68605581 44.94184816
  50.54792754 49.6819077  50.04319584]
 [48.92015519 52.29490669 55.43652785 46.34327079 48.98810003 49.26029975
  50.39402024 51.34948392 49.39626757]
 [47.84116346 49.49221049 48.94991245 51.04337401 50.60139912 48.91784929
  51.83058001 46.86500115 48.55730066]
 [47.46727048 47.45964181 50.81830061 46.6314446  46.79668435 50.37822787
  51.01000439 51.67909722 49.33246245]
 [54.40258467 48.6136382  48.39901026 53.99558576 48.59062384 48.69786827
  49.38934394 47.85774

In [9]:
a = np.random.normal(loc=50, scale=2, size=(9000000,900000000))
print(a)

MemoryError: 

In [10]:
a.savetxt(r'C:\Users\Public\Documents\Python Scripts\test.txt')

AttributeError: 'numpy.ndarray' object has no attribute 'savetxt'

In [12]:
np.savetxt(r'C:\Users\Public\Documents\Python Scripts\test.txt',a)

In [14]:
l = np.loadtxt(r'C:\Users\Public\Documents\Python Scripts\test.txt')
print (l)

[[47.28263851 49.6069657  47.03924067 50.13935578 49.71362691 51.23813159
  48.33797637 51.69460794 46.65717089]
 [51.74851218 46.72883672 50.83026388 53.91315674 49.5034558  50.19988648
  51.54134509 46.94918582 50.860565  ]
 [50.31125702 48.95860099 46.26288608 51.39589887 50.30956096 51.06477228
  53.15788133 49.68594131 51.20046254]
 [52.28509254 51.72533024 48.86189943 50.20274912 51.46234691 50.31044139
  49.82077989 50.59331497 52.89676008]
 [49.7282847  51.21506037 49.93792927 52.79981236 46.68605581 44.94184816
  50.54792754 49.6819077  50.04319584]
 [48.92015519 52.29490669 55.43652785 46.34327079 48.98810003 49.26029975
  50.39402024 51.34948392 49.39626757]
 [47.84116346 49.49221049 48.94991245 51.04337401 50.60139912 48.91784929
  51.83058001 46.86500115 48.55730066]
 [47.46727048 47.45964181 50.81830061 46.6314446  46.79668435 50.37822787
  51.01000439 51.67909722 49.33246245]
 [54.40258467 48.6136382  48.39901026 53.99558576 48.59062384 48.69786827
  49.38934394 47.85774

In [15]:
print(l.ndim)

2


In [16]:

print(l.shape)

(9, 9)


In [17]:
print(l.dtype)

float64


In [18]:
o = np.ones((4,4))
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
print(3*o-1)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
